name: build

on: [push, pull_request]

jobs:
  test:
    name: Go ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

      - uses: actions/checkout@v1

      - name: Setup go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.1

      - name: Build and Install
        run: |
          go run build/make.go
          go run build/make.go --install